### ISSUE TITLE
problem with extension (NumpyMarchingCubes)

### ISSUE THREAD

**Issue by DeepJackNotFound** [HengyiWang/Co-SLAM#14]
Hey there, I was trying to build this extension but it seems not working, I don't know if it is a problem with my VS.  Or Co-SLAM can not work on windows? Or can I Ignore this extension?

here is the last line for my error: 

error: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.36.32532\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2

**Comment by HengyiWang** [comment]
Hi @DeepJackNotFound, thanks for your question. This error message indicates the compile error and does not contain the reason why it happens. May I ask if you can share the specific error messages that precede this "failed with exit code 2" message? 

For NumpyMarchingCubes, it is used for extracting the mesh. You can probably change it to some other packages by modifying a bit of the code.
