### ISSUE TITLE
Questions about tiny-cuda-nn in your code and possibility to extend to unbounded scene exploring

### ISSUE THREAD

**Issue by laliwang** [HengyiWang/Co-SLAM#16]
Thank you for sharing your excellent work!
When I read your code, I notice that you predefine the bounding of scenes just like Nice-slam. And for the implementation of your joint representation, you mainly depend the tiny-cuda-nn to get encoding function easily, which is convenient but abstract compared to self-designed encoding function.
Thus my main concern may be **whether the encoding function provided by tiny-cuda-nn can be used to encode unbounded scene incrementally**, just like Vox-Fusion and H2-Mapping. Because I have noticed that tiny-cuda-nn requires normalized coordinate input, which is impractical for robots in unknown scenes.
I'd appreciate for your excellent work and profound reply!

**Comment by HengyiWang** [comment]
Hi @laliwang, thank you for your interest in our work. Adapting our approach to handle unbounded scenes would require some engineering effort. 

In our current implementation, joint encoding is designed to cover a specific area that is pre-defined using scene bound. However, if the predefined bounding is not enough to cover your depth map, you can initialize a new joint encoding to cover the new area. This should be similar to Vox-Fusion (Allocate new voxels to cover visible area incrementally) and H2-Mapping (Allocate new voxels to cover visible area incrementally and use hash encoding to fit residual of initial estimation).

I hope this provides some guidance for incorporating our approach into unbounded scenes. If you have any further questions or need additional clarification, please let me know.
