### ISSUE TITLE
Does the hash code have to be normalized?

### ISSUE THREAD

**Issue by ZZy129326999** [HengyiWang/Co-SLAM#17]
Hello, does the hash code have to be normalized?

**Comment by HengyiWang** [comment]
Hi @ZZy129326999, sorry I do not quite understand your question. May I ask what you mean by hash code has to be normalized? Do you mean the feature of the hash grid or do you mean the coordinate to query the feature from the hash grid?

**Comment by ZZy129326999** [comment]
I mean that coordinate to query the feature from the hash grid.

**Comment by HengyiWang** [comment]
Hi @ZZy129326999, yes, the tiny-cuda-nn requires the input coordinate to be normalized.
