### ISSUE TITLE
How to visualize the process of online construction？

### ISSUE THREAD

**Issue by ZZy129326999** [HengyiWang/Co-SLAM#18]
Hello, how to visualize the process of online construction.

**Comment by ZZy129326999** [comment]
I've made it! Thank you!

**Comment by ZorAttC** [comment]
Can you share your codes or the method to visualize online?I will greatly appreciate it .

**Comment by ArlenCHEN** [comment]
Hi, @ZZy129326999, could you please share how you made it? Thanks!

**Comment by BloodLemonS** [comment]
> Hi, @ZZy129326999, could you please share how you made it? Thanks!

Have you been made it？

**Comment by Ruihyw** [comment]
> Have you been made it？

Hi,have u been made it?
