### ISSUE TITLE
sdf_mask and fs_weight in get_masks

### ISSUE THREAD

**Issue by mian-zhi** [HengyiWang/Co-SLAM#34]
Hello Ph.D, in the get_masks function of Model / Utils.py, 
calculate
```
fs_weight` = 1.0 -num_fs_samples / num_samples
sdf_weight = 1.0 -num_sdf_samples / num_samples
```
Is it inconsistent with the formula in the paper? Whether it should be:
```
fs_weight = num_fs_samples / num_samples
sdf_weight = num_sdf_samples / num_samples
```

**Comment by mian-zhi** [comment]
If all the sampling points fall in the cut -off area, according to the original code, then the SDF_Weight will be 0, and the fs_weight will be 1.

**Comment by HengyiWang** [comment]
Hi @mian-zhi, this is a strategy for balancing the weight of SDF and free space. For each ray, most of the sampled points would be in free space, which will make the MLP biased toward free space. Thus, we need to use this weight to balance the SDF and free space loss.

**Comment by mian-zhi** [comment]
I understand. Thank you, Doctor.

**Comment by akawincent** [comment]
> Hello Ph.D, in the get_masks function of Model / Utils.py, calculate
> 
> ```
> fs_weight` = 1.0 -num_fs_samples / num_samples
> sdf_weight = 1.0 -num_sdf_samples / num_samples
> ```
> 
> Is it inconsistent with the formula in the paper? Whether it should be:
> 
> ```
> fs_weight = num_fs_samples / num_samples
> sdf_weight = num_sdf_samples / num_samples
> ```

That is a good question! 
It was also confused me. Thanks for your answer. @HengyiWang
