### ISSUE TITLE
Neural RGBG Data

### ISSUE THREAD

**Issue by Hnshlr** [HengyiWang/Co-SLAM#4]
Hi Hengyi, the neural RGBD data sequences can't be downloaded at the moment. Would you happen to know why? (https://kaldir.vc.in.tum.de/ can't be accessed at all)
Great work btw!

**Comment by HengyiWang** [comment]
Thank you for bringing this to my attention @Hnshlr. It can not be accessed by the moment you raise the issue, but it appears to be working fine now. Please try accessing the link (http://kaldir.vc.in.tum.de/neural_rgbd/neural_rgbd_data.zip) to see if you are able to download the dataset:)

**Comment by Hnshlr** [comment]
It is indeed working fine now, tysm for your quick response :D
