### ISSUE TITLE
Pose evaluation graph issues using Replica Dataset Office_0

### ISSUE THREAD

**Issue by saulgooodman** [HengyiWang/Co-SLAM#41]
When I was using Replica Dataset Office_0 as the dataset, I found the predicted trajectory map and the ground truth trajectory map exhibit similar shapes but differ significantly in scale, with an approximate discrepancy of 5x.
Could you please explain why this happened? Is this issue happening during drawing using Matplotlib, or is it due to errors in pose estimation during Bundle Adjustment (BA)? In other words, does this plotting with Matplotlib indicate a potential impact on SLAM performance?
Thanks a lot!
![pose_500](https://github.com/HengyiWang/Co-SLAM/assets/91330822/fe1bba95-3738-4807-8f35-473901cd955b)

**Comment by HengyiWang** [comment]
Hi @saulgooodman, I am not sure what is going on here. I have never observed this issue before. Can you check if you downloaded everything correctly and have not changed any configs?

**Comment by saulgooodman** [comment]
Yeah, I have downloaded everything correctly and I used the default config (except num_workers changed from 4 to 0 but it shouldn't have any effect on plotting the graph ). BTW I tested PSNR of the rendering result (PSNR=27.29) , the PSNR seems OK.

**Comment by HengyiWang** [comment]
Can you check whether the reconstructed mesh aligns with the ground-truth mesh (Without any significant difference in scale)? Additionally, please also make sure you turn on the SDF loss or depth loss.

**Comment by saulgooodman** [comment]
SDF loss and depth loss are turned on. However there exists a scale error between GT and the output :(   
![ERROR](https://github.com/HengyiWang/Co-SLAM/assets/91330822/77707a58-1aae-4c5b-86f1-0aa2e0cf2eac)

**Comment by HengyiWang** [comment]
That is so weird. I have never experienced this behavior before. Can you check your data (depth map) and see if you have set up a correct depth scale in the config file? I guess there must be something wrong with the data, or configs in your case. Maybe you can follow the instructions in the README to download the repository as well as the replica scene again and re-run Co-SLAM if you still cannot figure out what caused this issue.

**Comment by saulgooodman** [comment]
I chose another version of Replica and the scale returned to normal! Thanks to your patience! :)
