### ISSUE TITLE
Regarding License

### ISSUE THREAD

**Issue by Huangying-Zhan** [HengyiWang/Co-SLAM#46]
Hi @HengyiWang, thanks for open source this impressive project.  I am interested in using your project for our research project, but I noticed that the repository currently lacks a clear license file. A license would provide guidance on how your project can be used, modified, or shared by others.
Would you consider adding a standard open-source license to your repository?

**Comment by HengyiWang** [comment]
Have added it:)

**Comment by Huangying-Zhan** [comment]
Thanks Hengyi!
